---
- name: Add acl configuration master
  template:
    src: consul.master.j2
    dest: "{{ consul_configdir }}/master.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  notify: restart consul
  when: consul_server

- name: Add acl configuration client
  template:
    src: consul.client.j2
    dest: "{{ consul_configdir }}/client.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  notify: restart consul
  when: consul_agent

- name: ACLs system needs to be enabled prior to apply them
  meta: flush_handlers

- name: Consul | Install consul_acl prerequisites
  apt:
    name: "{{ item }}"
  with_items:
    - python-pip
    - openssl

- name: Consul | Install consul_acl Python prerequisites
  pip:
    name: "{{ item }}"
  with_items:
    - python-consul
    - pyhcl
    - requests

- name: Consul | Wait for Consul to start up
  wait_for:
    port: "{{ consul_http_port }}"
    timeout: 60

- name: Consul | Create ACL
  consul_acl:
    name: "{{ item.key }}"
    token_type: "{{ item.value.token_type }}"
    token: "{{ item.value.token }}"
    rules: "{{ item.value.rules }}"
    mgmt_token: "{{ consul_acl_master_token }}"
    host: "{{ consul_server_nodes | first }}"
  notify: restart consul
  with_dict: "{{ consul_acl_configuration_list }}"
